// <auto-generated />
using System;
using EventPlatformAPI.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventPlatformAPI.Web.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260328155919_db_seeded")]
    partial class db_seeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agenda")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DurationInHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("TypeId");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Agenda = "Pregled novina u .NET platformi",
                            DateTime = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInHours = 6.00m,
                            LocationId = 1,
                            Name = "Savremene .NET tehnologije",
                            Price = 3500.00m,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Agenda = "Osnovni principi mikroservisne arhitekture",
                            DateTime = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationInHours = 4.00m,
                            LocationId = 2,
                            Name = "Uvod u mikroservise",
                            Price = 2500.00m,
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.EventLecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("EventId", "LecturerId", "DateTime")
                        .IsUnique();

                    b.ToTable("EventLecturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2026, 6, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            LecturerId = 1,
                            Theme = "Arhitektura modernih .NET aplikacija"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            LecturerId = 1,
                            Theme = "Performanse i optimizacija"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2026, 6, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            LecturerId = 2,
                            Theme = "Modelovanje servisa i baza"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stručna konferencija",
                            Name = "Konferencija"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Edukativni seminar",
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Praktična radionica",
                            Name = "Radionica"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Field = "Softversko inženjerstvo",
                            FirstName = "Milan",
                            LastName = "Petrović",
                            Title = "Prof. dr"
                        },
                        new
                        {
                            Id = 2,
                            Field = "Baze podataka",
                            FirstName = "Jelena",
                            LastName = "Jovanović",
                            Title = "Doc. dr"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bulevar kralja Aleksandra 73",
                            Capacity = 200,
                            Name = "Amfiteatar A"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kraljice Marije 16",
                            Capacity = 80,
                            Name = "Sala 101"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Event", b =>
                {
                    b.HasOne("EventPlatformAPI.Web.Domains.Location", "Location")
                        .WithMany("Events")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventPlatformAPI.Web.Domains.EventType", "Type")
                        .WithMany("Events")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.EventLecturer", b =>
                {
                    b.HasOne("EventPlatformAPI.Web.Domains.Event", "Event")
                        .WithMany("EventLecturers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPlatformAPI.Web.Domains.Lecturer", "Lecturer")
                        .WithMany("EventLecturers")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Event", b =>
                {
                    b.Navigation("EventLecturers");
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Lecturer", b =>
                {
                    b.Navigation("EventLecturers");
                });

            modelBuilder.Entity("EventPlatformAPI.Web.Domains.Location", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
