// <auto-generated />
using EventPlatformAPI.ReferencesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventPlatformAPI.ReferencesAPI.Migrations
{
    [DbContext(typeof(ReferenceDbContext))]
    [Migration("20260405110715_InitialReferenceSchema")]
    partial class InitialReferenceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventPlatformAPI.ReferencesAPI.Models.EventType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("EventTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Stru?na konferencija",
                            Name = "Konferencija"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Edukativni seminar",
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Prakti?na radionica",
                            Name = "Radionica"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.ReferencesAPI.Models.Lecturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Lecturers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Field = "Softversko inženjerstvo",
                            FirstName = "Milan",
                            LastName = "Petrovi?",
                            Title = "Prof. dr"
                        },
                        new
                        {
                            Id = 2,
                            Field = "Baze podataka",
                            FirstName = "Jelena",
                            LastName = "Jovanovi?",
                            Title = "Doc. dr"
                        });
                });

            modelBuilder.Entity("EventPlatformAPI.ReferencesAPI.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bulevar kralja Aleksandra 73",
                            Capacity = 200,
                            Name = "Amfiteatar A"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kraljice Marije 16",
                            Capacity = 80,
                            Name = "Sala 101"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
